// <auto-generated />
namespace Andpol.Dane.Migrations.Entities
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fakturaSprzedazy_korekta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fakturaSprzedazy_korekta));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091510033_fakturaSprzedazy_korekta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
