// <auto-generated />
namespace Andpol.Dane.Migrations.Entities
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fakturaSprzedazy_magWzIds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fakturaSprzedazy_magWzIds));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101456367_fakturaSprzedazy_magWzIds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
